sudo: true

dist: xenial

env:
  global:
    - KUBECTL_VERSION=1.10.6
    - KUBERNETES_VERSION=1.10.6
    - MINIKUBE_VERSION=0.28.2

install:
  - source .ci/install_minikube.sh
  - source .ci/install_knative.sh

script:
  - kubectl cluster-info
  - echo 'Knative ingress:' $(minikube ip):$(kubectl get svc knative-ingressgateway -n istio-system -o 'jsonpath={.spec.ports[?(@.port==80)].nodePort}')
  - eval $(minikube docker-env)
  - echo "OK"
  - docker ps
  - docker build -t helloworld-go .
  - kubectl apply -f service.yml