sudo: true

dist: xenial

env:
  global:
    - KUBECTL_VERSION=1.10.6
    - KUBERNETES_VERSION=1.10.6
    - MINIKUBE_VERSION=0.28.2

install:
  - source .ci/install_minikube.sh
  - source .ci/install_knative.sh
  - kubectl cluster-info

script:
  - source .ci/build_app.sh
  - curl -H "Host: ${HOST_URL}" http://${IP_ADDRESS}/world