apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helloworld-go
  namespace: default
  labels:
    app: helloworld-go
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: helloworld-go
            imagePullPolicy: Never